version: '3.1'
services:
  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
 #   restart: always
    depends_on:
      - stats-db
      - ewm-db
      - stats-server
    ports:
      - "8080:8080"
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SERVICE_DB_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    build: ./stats-server
    container_name: stats-server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STATS_DB_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    restart: always
    volumes:
      - /var/lib/postgresql/data2/
    ports:
      - "5555:5432"
    command: -p 5432
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-db:
    image: postgres:14-alpine
    restart: always
    container_name: ewm-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "7777:5432"
    command: -p 5432
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
